import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="flex flex-col flex-1 items-center bg-zinc-50 dark:bg-black">
      <header className="w-full border-b border-zinc-200 dark:border-zinc-800">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-lg font-bold text-zinc-900 dark:text-white">
            AutoPost Nepal
          </Link>
          <nav className="flex items-center gap-4 text-sm">
            <Link href="/login" className="px-4 py-1.5 rounded-lg border border-zinc-300 dark:border-zinc-700 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-800">
              Login
            </Link>
            <Link href="/register" className="px-4 py-1.5 rounded-lg bg-zinc-900 text-white dark:bg-white dark:text-zinc-900 hover:opacity-90">
              Get Started
            </Link>
          </nav>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-zinc-900 dark:text-white mb-8">
          Terms of Service
        </h1>

        <div className="space-y-6 text-zinc-600 dark:text-zinc-400 text-sm leading-relaxed">
          <p><strong className="text-zinc-900 dark:text-white">Last updated:</strong> July 3, 2026</p>

          <h2 className="text-xl font-semibold text-zinc-900 dark:text-white">1. Service Description</h2>
          <p>
            AutoPost Nepal is an automated content posting service that generates motivational,
            philosophical, and language-learning content and publishes it to Facebook and TikTok
            on a daily schedule. The service is fully automated and operates without human
            intervention in content generation or posting.
          </p>

          <h2 className="text-xl font-semibold text-zinc-900 dark:text-white">2. Use of Service</h2>
          <p>
            By using this service, you agree that content is generated by an AI model (DeepSeek)
            and may not always be accurate, appropriate, or error-free. We make no guarantees
            about the quality, relevance, or safety of the generated content.
          </p>

          <h2 className="text-xl font-semibold text-zinc-900 dark:text-white">3. API Usage</h2>
          <p>
            This service interacts with third-party APIs including Facebook Graph API and TikTok
            Content API. Availability of the service depends on the uptime and rate limits of
            these third-party platforms.
          </p>

          <h2 className="text-xl font-semibold text-zinc-900 dark:text-white">4. Limitation of Liability</h2>
          <p>
            AutoPost Nepal is provided &quot;as is&quot; without warranties of any kind. We are not
            liable for any damages arising from the use or inability to use this service,
            including but not limited to content that may be flagged, removed, or result in
            account restrictions on third-party platforms.
          </p>

          <h2 className="text-xl font-semibold text-zinc-900 dark:text-white">5. Changes</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the service
            after changes constitutes acceptance of the new terms.
          </p>

          <h2 className="text-xl font-semibold text-zinc-900 dark:text-white">6. Contact</h2>
          <p>
            For questions about these terms, please contact the service administrator.
          </p>
        </div>
      </main>

      <footer className="w-full border-t border-zinc-200 dark:border-zinc-800 py-6 text-center text-sm text-zinc-500 dark:text-zinc-500">
        &copy; {new Date().getFullYear()} AutoPost Nepal.{" "}
        <Link href="/privacy" className="underline hover:text-zinc-700 dark:hover:text-zinc-300">Privacy</Link>
      </footer>
    </div>
  );
}
